services:
  api:
    container_name: multi_tenancy_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - multi_tenancy-network
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./src:/app/src
      - /app/node_modules
      - /app/dist
    command: npm run start:dev
    restart: unless-stopped
    
  postgres:
    image: postgres:15
    container_name: multi_tenancy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multi_tenancy  # This creates the database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - multi_tenancy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d multi_tenancy"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: multi_tenancy_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - multi_tenancy-network
    command: redis-server --appendonly yes
  pgadmin:
    image: dpage/pgadmin4
    container_name: multi_tenancy_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - multi_tenancy-network
    depends_on:
      - postgres
      
networks:
  multi_tenancy-network:
    driver: bridge
    
volumes:
  postgres_data:
  redis_data: 