version: "3.9"

services:
  api:
    container_name: multi_tenancy_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - multi_tenancy-network
    volumes:
      - .:/app
      # - /app/node_modules
    command: npm run start:dev
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: multi_tenancy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multi_tenancy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - multi_tenancy-network

networks:
  multi_tenancy-network:
    driver: bridge

volumes:
  postgres_data:
